### ISSUE TITLE
Call Dash without activating it

### ISSUE THREAD

**Issue by Kapeli** [ram-nadella/DashMate.tmbundle#17]
DashMate calls Dash by opening a `dash://` URL. The problem is that the system forces Dash to become active when this URL is opened.

Currently, this is not an issue. However, a future update of Dash will add support for iOS remotes. While an iOS remote is connected, extensions are redirected to it directly and Dash on OS X is not shown at all. Unfortunately there's no way for me to prevent the system from activating Dash when you open the `dash://` URL.

Instead of doing this:
```
open dash://query
```

Can you do this?
```
open -g dash://query
```

The `-g` causes Dash to not get activated if it does not want to and the user experience is a lot better as the active app does not lose focus anymore.

It is safe to make this change as soon as possible (no need to wait for a Dash update), as the current version of Dash already knows to activate itself if it needs to.

**Comment by ram-nadella** [comment]
Thanks for the heads up about the remote changes.

I am happy to make a change to support the use case you mentioned, but it seems like adding a -g by default makes it always be in the background, which would break the expectation some people might have about seeing the docs in Dash when they press the key.

Is there any way we can support both cases - both foreground and background?

**Comment by Kapeli** [comment]
If you add `-g` you just let Dash decide whether or not to show. Right now, if you add `-g` nothing will change, Dash will just show as usual because it activates itself.

**Comment by ram-nadella** [comment]
Oh, that's good!

Made the [change](https://github.com/ram-nadella/DashMate.tmbundle/commit/a7faf7740833e1ec3c8ebf5b97eaf67627685bd4). We are all set.

**Comment by Kapeli** [comment]
Thank you! :+1:
